In [123]:
import numpy as np
import pandas as pd
import ast

In [124]:
movies= pd.read_csv("tmdb_5000_movies.csv")
credits= pd.read_csv("tmdb_5000_credits.csv")

In [125]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [126]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [127]:
movies= movies.merge(credits,on= 'title')

In [128]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [129]:
movies['original_language'].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

In [130]:
movies= movies[['movie_id', 'title', 'overview', 'genres', 'keywords','cast','crew']]

In [131]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [132]:
movies.dropna(inplace=True)

In [133]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [134]:
movies.duplicated().sum()

0

In [135]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [136]:
def convert(obj):
    tag= []
    for i in ast.literal_eval(obj):
        tag.append(i['name'])
    return tag

In [137]:
movies['genres']= movies['genres'].apply(convert)

In [138]:
movies['keywords']= movies['keywords'].apply(convert)

In [139]:
def convert3(obj):
    tag= []
    for i,j in zip(ast.literal_eval(obj),range(3)):
        tag.append(i['character'])
    return tag

In [140]:
movies['cast']= movies['cast'].apply(convert3)

In [141]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Jake Sully, Neytiri, Dr. Grace Augustine]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain Jack Sparrow, Will Turner, Elizabeth ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[James Bond, Blofeld, Madeleine]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Bruce Wayne / Batman, Alfred Pennyworth, Jame...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John Carter, Dejah Thoris, Sola]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [142]:
def convertdir(obj):
    tag= []
    for i in ast.literal_eval(obj):
        if i['job']=='Director':  
          tag.append(i['name'])
          break
    return tag

In [143]:
movies['crew']= movies['crew'].apply(convertdir)

In [144]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Jake Sully, Neytiri, Dr. Grace Augustine]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[James Bond, Blofeld, Madeleine]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Bruce Wayne / Batman, Alfred Pennyworth, Jame...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John Carter, Dejah Thoris, Sola]",[Andrew Stanton]

In [145]:
movies['overview']= movies['overview'].apply(lambda x:x.split())

In [146]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Jake Sully, Neytiri, Dr. Grace Augustine]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain Jack Sparrow, Will Turner, Elizabeth ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[James Bond, Blofeld, Madeleine]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Bruce Wayne / Batman, Alfred Pennyworth, Jame...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John Carter, Dejah Thoris, Sola]",[Andrew Stanton]

In [147]:
movies['genres']= movies['genres'].apply(lambda x:[i.replace(' ','') for i in x])
movies['cast']= movies['cast'].apply(lambda x:[i.replace(' ','') for i in x])
movies['crew']= movies['crew'].apply(lambda x:[i.replace(' ','') for i in x])
movies['keywords']= movies['keywords'].apply(lambda x:[i.replace(' ','') for i in x])

In [148]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[JakeSully, Neytiri, Dr.GraceAugustine]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[CaptainJackSparrow, WillTurner, ElizabethSwann]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[JamesBond, Blofeld, Madeleine]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[BruceWayne/Batman, AlfredPennyworth, JamesGor...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[JohnCarter, DejahThoris, Sola]",[AndrewStanton]

In [149]:
movies['tags']= movies['overview']+movies['genres']+movies['crew']+movies['cast']+movies['keywords']
movies['tags']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: tags, Length: 4806, dtype: object

In [150]:
new_df= movies[['movie_id','title','tags']]
new_df['tags']

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: tags, Length: 4806, dtype: object

In [151]:
new_df['tags']= new_df['tags'].apply(lambda x:' '.join(x))

C:\Users\tanim\AppData\Local\Temp\ipykernel_5580\3391018727.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:' '.join(x))

In [152]:
new_df['tags']= new_df['tags'].apply(lambda x:x.lower())

C:\Users\tanim\AppData\Local\Temp\ipykernel_5580\899821970.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:x.lower())

In [153]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000, stop_words='english')

In [154]:
import nltk

In [155]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [156]:
def stem(text):
    y= []
    for i in text.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [157]:
new_df['tags']= new_df['tags'].apply(stem)

C:\Users\tanim\AppData\Local\Temp\ipykernel_5580\3021978705.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(stem)

In [158]:
vectors= cv.fit_transform(new_df['tags']).toarray()

In [159]:
print(cv.get_feature_names_out())

['000' '007' '10' ... 'zombies' 'zone' 'zoo']

In [160]:
from sklearn.metrics.pairwise import cosine_similarity

In [161]:
similarity= cosine_similarity(vectors)

In [162]:
sorted(list(enumerate(similarity[0])),reverse= True,key= lambda x:x[-1])

[(0, 1.0000000000000002),
 (1216, 0.2773500981126146),
 (2409, 0.26257545381445874),
 (507, 0.2591001102525183),
 (539, 0.25883878884437284),
 (61, 0.24459979523511427),
 (3730, 0.24459979523511427),
 (582, 0.2442635754263801),
 (1204, 0.24140227479263376),
 (1194, 0.23897605969962157),
 (778, 0.23357091793352583),
 (1920, 0.23357091793352583),
 (4048, 0.2204155075111935),
 (168, 0.21209492099192592),
 (322, 0.21059925059706258),
 (151, 0.20483662259967564),
 (1321, 0.20483662259967564),
 (220, 0.2046468711716401),
 (2786, 0.2046468711716401),
 (260, 0.2013190579900678),
 (172, 0.20033416898825335),
 (1444, 0.20016019225635892),
 (74, 0.1998520162579474),
 (1089, 0.19944037418082106),
 (2333, 0.19611613513818402),
 (3608, 0.19562767576168477),
 (3327, 0.19418390934515434),
 (3675, 0.19312181983410703),
 (972, 0.19223226273338134),
 (973, 0.19223226273338134),
 (577, 0.18946618668626833),
 (4, 0.18887686585995425),
 (4192, 0.18842228790639834),
 (595, 0.18685673434682068),
 (2970, 0.18681617943926832),
 (4405, 0.18490006540840973),
 (2999, 0.18367958959266126),
 (27, 0.18302666282596894),
 (529, 0.18300360434867097),
 (1071, 0.18183351671314588),
 (1275, 0.1815682598006407),
 (2971, 0.1813094310734737),
 (373, 0.17902871850985821),
 (495, 0.17841031003501578),
 (3999, 0.17841031003501576),
 (342, 0.17792017089454126),
 (83, 0.177646236673731),
 (1537, 0.177646236673731),
 (305, 0.17739371879672478),
 (549, 0.17596234808583347),
 (513, 0.17295817388759027),
 (2204, 0.17295817388759027),
 (4336, 0.17295817388759027),
 (1329, 0.17255919256291524),
 (91, 0.16984155512168933),
 (36, 0.16898159235484367),
 (67, 0.16898159235484367),
 (47, 0.16867424537771253),
 (931, 0.16724840200141816),
 (41, 0.167093470609201),
 (3634, 0.1653796461189446),
 (95, 0.16526725762745997),
 (1201, 0.16477051091432687),
 (3093, 0.16401847362094596),
 (150, 0.1621424235993525),
 (300, 0.16178755723235852),
 (56, 0.16012815380508716),
 (461, 0.16012815380508713),
 (1178, 0.16012815380508713),
 (3538, 0.1585187847802434),
 (2515, 0.15701857325533194),
 (184, 0.15695698526580623),
 (149, 0.15534712747612348),
 (4010, 0.15534712747612348),
 (581, 0.15408338784034142),
 (661, 0.15311180047019055),
 (1965, 0.15311180047019055),
 (412, 0.15253477177414312),
 (942, 0.15253477177414312),
 (75, 0.15191090506255),
 (1383, 0.15191090506255),
 (94, 0.1513068831672006),
 (1373, 0.1513068831672006),
 (2731, 0.1513068831672006),
 (4018, 0.1513068831672006),
 (1348, 0.15097027121927944),
 (26, 0.1500468969841066),
 (311, 0.1500468969841066),
 (275, 0.14867525836251314),
 (52, 0.14824986333222023),
 (111, 0.14824986333222023),
 (1982, 0.14824986333222023),
 (7, 0.14651588715165131),
 (1344, 0.1465158871516513),
 (568, 0.14617633655117152),
 (920, 0.14617633655117152),
 (127, 0.14598637372036238),
 (108, 0.14484136487558028),
 (1355, 0.14484136487558028),
 (502, 0.14470719035407653),
 (1479, 0.14470719035407653),
 (838, 0.14412659875498),
 (1396, 0.1435161644183277),
 (466, 0.14322297480788657),
 (508, 0.14322297480788657),
 (935, 0.14322297480788657),
 (3162, 0.14235407108686474),
 (187, 0.1416576493949657),
 (334, 0.1416576493949657),
 (2075, 0.14153462926807445),
 (2760, 0.14121975762272052),
 (1938, 0.1401425507601155),
 (1831, 0.14011213457945124),
 (1878, 0.14011213457945124),
 (476, 0.13977131156292244),
 (490, 0.13977131156292244),
 (1327, 0.13977131156292244),
 (1297, 0.1386750490563073),
 (17, 0.13797289239745258),
 (31, 0.1373087590952724),
 (579, 0.1373087590952724),
 (843, 0.1373087590952724),
 (3409, 0.1373087590952724),
 (4079, 0.1373087590952724),
 (668, 0.13655774839978377),
 (72, 0.13533299049019168),
 (2169, 0.13533299049019168),
 (4538, 0.1345345587992625),
 (134, 0.13355611265883557),
 (505, 0.13355611265883557),
 (1488, 0.13355611265883557),
 (3954, 0.13355611265883557),
 (3982, 0.13355611265883557),
 (859, 0.13344012817090595),
 (1015, 0.13344012817090595),
 (1031, 0.13344012817090595),
 (3354, 0.13344012817090595),
 (4348, 0.13323467750529824),
 (1497, 0.13302600912742518),
 (3431, 0.13212766396701017),
 (777, 0.1319717610643751),
 (413, 0.1316245316231641),
 (1560, 0.1316245316231641),
 (2496, 0.1316245316231641),
 (483, 0.1307440900921227),
 (487, 0.1307440900921227),
 (2378, 0.1307440900921227),
 (3781, 0.1307440900921227),
 (182, 0.13074409009212268),
 (2133, 0.13074409009212268),
 (46, 0.12988108336653278),
 (294, 0.12988108336653278),
 (1273, 0.1283881477532739),
 (3083, 0.1283881477532739),
 (4343, 0.1283881477532739),
 (14, 0.1282051282051282),
 (306, 0.1282051282051282),
 (1086, 0.1282051282051282),
 (1808, 0.1282051282051282),
 (2181, 0.1282051282051282),
 (3622, 0.1282051282051282),
 (368, 0.12810252304406972),
 (773, 0.12810252304406972),
 (1158, 0.12810252304406972),
 (2584, 0.12810252304406972),
 (2873, 0.12725695259515554),
 (158, 0.126155140059354),
 (1774, 0.12561485860426555),
 (2060, 0.12561485860426555),
 (2323, 0.12561485860426555),
 (239, 0.12532010295690074),
 (102, 0.12508145976752497),
 (138, 0.12503908082008883),
 (438, 0.12503908082008883),
 (3628, 0.12503908082008883),
 (2480, 0.12403473458920844),
 (70, 0.1235415527768502),
 (557, 0.1235415527768502),
 (2450, 0.1235415527768502),
 (4230, 0.1235415527768502),
 (208, 0.12326671027227314),
 (249, 0.12326671027227314),
 (356, 0.12326671027227314),
 (1096, 0.12326671027227314),
 (1274, 0.12326671027227314),
 (1658, 0.12326671027227314),
 (84, 0.12301385521570944),
 (1322, 0.1215783580010781),
 (678, 0.12104550653376048),
 (781, 0.12104550653376048),
 (1047, 0.12104550653376048),
 (1474, 0.12104550653376048),
 (1756, 0.12104550653376048),
 (2652, 0.12104550653376048),
 (369, 0.1207011373963169),
 (2284, 0.1207011373963169),
 (1002, 0.12009611535381536),
 (850, 0.12009611535381534),
 (2331, 0.12009611535381534),
 (126, 0.11935247900657214),
 (900, 0.11935247900657214),
 (2135, 0.11916871834484359),
 (3376, 0.11894020669001051),
 (3736, 0.11894020669001051),
 (4673, 0.11894020669001051),
 (139, 0.1182624791978165),
 (3235, 0.11804804116247142),
 (278, 0.1180480411624714),
 (1056, 0.1180480411624714),
 (2488, 0.1180480411624714),
 (1741, 0.11737660545701087),
 (422, 0.11694106924093722),
 (2741, 0.11694106924093722),
 (166, 0.11678545896676293),
 (454, 0.11678545896676293),
 (814, 0.11678545896676293),
 (808, 0.11651034560709261),
 (1575, 0.11651034560709261),
 (1673, 0.11651034560709261),
 (2674, 0.11651034560709261),
 (2789, 0.11651034560709261),
 (1009, 0.11556254088025608),
 (1617, 0.11556254088025608),
 (50, 0.11503946170861017),
 (236, 0.11503946170861017),
 (1004, 0.11503946170861017),
 (1301, 0.11503946170861017),
 (1833, 0.11503946170861017),
 (536, 0.11437725271791938),
 (3905, 0.114022293537793),
 (3212, 0.11357879791108),
 (189, 0.11322770341445959),
 (205, 0.11322770341445959),
 (4587, 0.11322770341445959),
 (432, 0.11322770341445958),
 (1299, 0.11322770341445958),
 (2547, 0.11322770341445958),
 (2820, 0.11322770341445958),
 (4265, 0.11322770341445958),
 (28, 0.11322770341445956),
 (121, 0.11322770341445956),
 (122, 0.11322770341445956),
 (449, 0.11322770341445956),
 (1616, 0.11322770341445956),
 (3866, 0.11322770341445956),
 (85, 0.11265439490322912),
 (301, 0.11244949691847501),
 (420, 0.11211213233271873),
 (1418, 0.11211213233271873),
 (2686, 0.11211213233271873),
 (889, 0.112089707663561),
 (1361, 0.11168711865749101),
 (160, 0.1115334277650088),
 (775, 0.11149893466761211),
 (1589, 0.11149893466761211),
 (1945, 0.11149893466761211),
 (228, 0.11102889792108188),
 (870, 0.11102889792108188),
 (589, 0.11094003924504582),
 (3147, 0.11094003924504581),
 (200, 0.11020775375559674),
 (233, 0.11020775375559674),
 (627, 0.11020775375559674),
 (653, 0.11020775375559674),
 (1033, 0.11020775375559674),
 (1501, 0.11020775375559674),
 (2161, 0.11020775375559674),
 (937, 0.10997646755364592),
 (21, 0.10984700727621793),
 (87, 0.10984700727621793),
 (3008, 0.10984700727621793),
 (4468, 0.10984700727621793),
 (81, 0.10948978029027179),
 (123, 0.10895340841010223),
 (1896, 0.10895340841010223),
 (2372, 0.10895340841010223),
 (3309, 0.10895340841010223),
 (238, 0.10878565864408421),
 (307, 0.10836121044482576),
 (3428, 0.10826639239215335),
 (472, 0.10826639239215334),
 (1237, 0.10826639239215334),
 (2072, 0.10826639239215334),
 (1512, 0.10795837927188263),
 (1220, 0.10795837927188262),
 (3553, 0.10795837927188262),
 (229, 0.10741723110591493),
 (105, 0.10741723110591492),
 (1770, 0.10741723110591492),
 (2521, 0.10741723110591492),
 (262, 0.10699012312772824),
 (295, 0.10675210253672475),
 (332, 0.10675210253672475),
 (786, 0.10675210253672475),
 (3498, 0.10675210253672475),
 (4097, 0.10675210253672475),
 (1574, 0.1060991783534611),
 (674, 0.10604746049596296),
 (939, 0.10545808983558423),
 (68, 0.10529962529853128),
 (232, 0.10529962529853128),
 (687, 0.10529962529853128),
 (1771, 0.10529962529853128),
 (3340, 0.10529962529853128),
 (170, 0.105129283382795),
 (572, 0.105129283382795),
 (754, 0.105129283382795),
 (3630, 0.105129283382795),
 (209, 0.10482848367219183),
 (319, 0.10482848367219183),
 (1280, 0.10482848367219183),
 (2456, 0.10482848367219183),
 (2634, 0.10482848367219183),
 (3055, 0.10482848367219183),
 (3721, 0.10482848367219183),
 (4431, 0.10482848367219183),
 (1496, 0.10423454980627081),
 (2817, 0.10390486669322622),
 (467, 0.10336227882434038),
 (1455, 0.10336227882434038),
 (174, 0.10256410256410256),
 (207, 0.10256410256410256),
 (312, 0.10256410256410256),
 (330, 0.10256410256410256),
 (1037, 0.10256410256410256),
 (1294, 0.10256410256410256),
 (2148, 0.10256410256410256),
 (675, 0.1025115460130912),
 (624, 0.10241831129983783),
 (1524, 0.10241831129983783),
 (1745, 0.10241831129983783),
 (3839, 0.10241831129983783),
 (4000, 0.10241831129983783),
 (4135, 0.10241831129983783),
 (1439, 0.10168147934776052),
 (2106, 0.10168147934776052),
 (223, 0.10127393670836667),
 (445, 0.10127393670836667),
 (632, 0.10127393670836667),
 (643, 0.10127393670836667),
 (988, 0.10127393670836667),
 (1195, 0.10127393670836667),
 (2091, 0.10127393670836667),
 (3923, 0.10127393670836667),
 (4226, 0.10127393670836667),
 (555, 0.10106788575898232),
 (541, 0.10087125544480038),
 (692, 0.10087125544480038),
 (740, 0.10087125544480038),
 (1405, 0.10087125544480038),
 (2264, 0.10087125544480038),
 (3441, 0.10087125544480038),
 (35, 0.10016708449412667),
 (2762, 0.10016708449412667),
 (650, 0.10003126465607107),
 (1082, 0.10003126465607107),
 (1614, 0.10003126465607107),
 (3152, 0.10003126465607107),
 (2099, 0.09930726528736966),
 (266, 0.09883324222148016),
 (480, 0.09883324222148016),
 (510, 0.09883324222148016),
 (535, 0.09883324222148016),
 (3011, 0.09883324222148016),
 (3022, 0.09883324222148016),
 (5, 0.09855206599818042),
 (654, 0.09855206599818042),
 (1534, 0.09855206599818042),
 (2498, 0.09855206599818042),
 (263, 0.09805806756909202),
 (660, 0.09805806756909202),
 (1027, 0.09805806756909202),
 (1156, 0.09805806756909202),
 (1166, 0.09805806756909202),
 (2053, 0.09805806756909202),
 (2562, 0.09805806756909202),
 (2787, 0.09805806756909202),
 (3537, 0.09805806756909202),
 (3663, 0.09805806756909202),
 (3891, 0.09805806756909202),
 (4490, 0.09805806756909202),
 (51, 0.09781383788084239),
 (1823, 0.09767725810110087),
 (2247, 0.09767725810110087),
 (3755, 0.09767725810110087),
 (371, 0.09656090991705352),
 (2241, 0.09656090991705352),
 (3874, 0.09656090991705352),
 (1775, 0.09638582199437336),
 (2439, 0.09638582199437336),
 (362, 0.09607689228305229),
 (715, 0.09607689228305229),
 (1077, 0.09607689228305229),
 (1721, 0.09607689228305229),
 (1727, 0.09607689228305229),
 (1942, 0.09607689228305229),
 (3621, 0.09607689228305229),
 (4331, 0.09607689228305229),
 (18, 0.0956948752938691),
 (10, 0.09548198320525772),
 (1430, 0.09548198320525772),
 (131, 0.09443843292997713),
 (1168, 0.09443843292997713),
 (1692, 0.09443843292997713),
 (2556, 0.09443843292997713),
 (3783, 0.09443843292997713),
 (491, 0.09435641951204965),
 (4024, 0.09421114395319917),
 (157, 0.09421114395319916),
 (219, 0.09421114395319916),
 (244, 0.09421114395319916),
 (256, 0.09421114395319916),
 (791, 0.09421114395319916),
 (1715, 0.09421114395319916),
 (1884, 0.09421114395319916),
 (4061, 0.09421114395319916),
 (4203, 0.09421114395319916),
 (363, 0.09370791409872918),
 (4545, 0.09370791409872918),
 (11, 0.09342836717341034),
 (410, 0.09342836717341034),
 (473, 0.09342836717341034),
 (543, 0.09342836717341034),
 (1445, 0.09342836717341034),
 (1996, 0.09342836717341034),
 (3620, 0.09342836717341034),
 (3838, 0.09342836717341034),
 (534, 0.09245003270420486),
 (596, 0.09245003270420486),
 (1109, 0.09245003270420486),
 (1457, 0.09245003270420486),
 (2850, 0.09245003270420486),
 (3462, 0.09245003270420486),
 (3935, 0.09245003270420486),
 (4777, 0.09245003270420486),
 (12, 0.09245003270420485),
 (148, 0.09245003270420485),
 (167, 0.09245003270420485),
 (230, 0.09245003270420485),
 (785, 0.09245003270420485),
 (1573, 0.09245003270420485),
 (2093, 0.09245003270420485),
 (2396, 0.09245003270420485),
 (2651, 0.09245003270420485),
 (4403, 0.09245003270420485),
 (243, 0.0915018021743355),
 (279, 0.0915018021743355),
 (587, 0.0915018021743355),
 (602, 0.0915018021743355),
 (898, 0.0915018021743355),
 (1401, 0.0915018021743355),
 (2650, 0.0915018021743355),
 (3407, 0.0915018021743355),
 (23, 0.09078412990032037),
 (511, 0.09078412990032037),
 (2645, 0.09078412990032037),
 (4198, 0.09078412990032037),
 (389, 0.09078412990032035),
 (59, 0.09065471553673685),
 (2570, 0.09065471553673685),
 (43, 0.09058216273156766),
 (1846, 0.09058216273156766),
 (2592, 0.09058216273156766),
 (9, 0.08968970586617499),
 (270, 0.08968970586617499),
 (331, 0.08968970586617499),
 (1233, 0.08968970586617499),
 (3389, 0.08968970586617499),
 (3443, 0.08968970586617499),
 (564, 0.08920515501750789),
 (1259, 0.08920515501750789),
 (1306, 0.08920515501750789),
 (1480, 0.08920515501750789),
 (2660, 0.08920515501750789),
 (3448, 0.08920515501750789),
 (3449, 0.08920515501750789),
 (4256, 0.08920515501750789),
 (274, 0.08889292040527026),
 (997, 0.0888231183368655),
 (1018, 0.0888231183368655),
 (1272, 0.0888231183368655),
 (1698, 0.0888231183368655),
 (3180, 0.0888231183368655),
 (4353, 0.0888231183368655),
 (813, 0.08798117404291673),
 (1783, 0.08798117404291673),
 (2109, 0.08798117404291673),
 (2713, 0.08798117404291673),
 (33, 0.08770580193070292),
 (292, 0.08770580193070292),
 (400, 0.08770580193070292),
 (597, 0.08770580193070292),
 (745, 0.08770580193070292),
 (1142, 0.08770580193070292),
 (2957, 0.08770580193070292),
 (799, 0.08735706972682653),
 (2448, 0.08735706972682653),
 (1019, 0.08716272672808179),
 (1175, 0.08716272672808179),
 (845, 0.08684168428648435),
 (143, 0.0863667034175061),
 (2740, 0.0863667034175061),
 (3556, 0.0863667034175061),
 (1, 0.08627959628145762),
 (2, 0.08627959628145762),
 (457, 0.08627959628145762),
 (1241, 0.08627959628145762),
 (2251, 0.08627959628145762),
 (2868, 0.08627959628145762),
 (3322, 0.08627959628145762),
 (2115, 0.08583770043743413),
 (32, 0.08559209850218259),
 (62, 0.08559209850218259),
 (206, 0.08559209850218259),
 (210, 0.08559209850218259),
 (718, 0.08559209850218259),
 (1276, 0.08559209850218259),
 (1530, 0.08559209850218259),
 (1664, 0.08559209850218259),
 (2253, 0.08559209850218259),
 (2856, 0.08559209850218259),
 (3006, 0.08559209850218259),
 (3720, 0.08559209850218259),
 (315, 0.08492077756084468),
 (1097, 0.08492077756084468),
 (1700, 0.08492077756084468),
 (2185, 0.08492077756084468),
 (3135, 0.08492077756084468),
 (129, 0.08483796839677037),
 (199, 0.08483796839677037),
 (217, 0.08483796839677037),
 (752, 0.08483796839677037),
 (1305, 0.08483796839677037),
 (1357, 0.08483796839677037),
 (1832, 0.08483796839677037),
 (2968, 0.08483796839677037),
 (3881, 0.08483796839677037),
 (169, 0.084103426706236),
 (383, 0.084103426706236),
 (1906, 0.084103426706236),
 (2527, 0.084103426706236),
 (179, 0.08362420100070908),
 (227, 0.08362420100070908),
 (894, 0.08362420100070908),
 (2583, 0.08362420100070908),
 (3301, 0.08362420100070908),
 (3356, 0.08362420100070908),
 (4754, 0.08362420100070908),
 (479, 0.08347257041177224),
 (827, 0.08338763984501665),
 (1639, 0.08338763984501665),
 (1701, 0.08338763984501665),
 (2203, 0.08338763984501665),
 (20, 0.08330923113952962),
 (381, 0.0826898230594723),
 (584, 0.0826898230594723),
 (618, 0.0826898230594723),
 (776, 0.0826898230594723),
 (2339, 0.0826898230594723),
 (2363, 0.0826898230594723),
 (2880, 0.0826898230594723),
 (3218, 0.0826898230594723),
 (3978, 0.0826898230594723),
 (4502, 0.0826898230594723),
 (2386, 0.08257978997938135),
 (626, 0.08238525545716345),
 (878, 0.08238525545716345),
 (1207, 0.08238525545716345),
 (1768, 0.08238525545716345),
 (4560, 0.08238525545716345),
 (48, 0.08200923681047297),
 (403, 0.08200923681047297),
 (455, 0.08134518347820842),
 (1202, 0.08134518347820842),
 (142, 0.081199794294115),
 (329, 0.081199794294115),
 (547, 0.081199794294115),
 (980, 0.081199794294115),
 (1749, 0.081199794294115),
 (2167, 0.081199794294115),
 (2304, 0.081199794294115),
 (2661, 0.081199794294115),
 (3470, 0.081199794294115),
 (4472, 0.081199794294115),
 (19, 0.0806970043558403),
 (45, 0.0806970043558403),
 (2354, 0.0806970043558403),
 (63, 0.08006407690254357),
 (164, 0.08006407690254357),
 (245, 0.08006407690254357),
 (349, 0.08006407690254357),
 (787, 0.08006407690254357),
 (866, 0.08006407690254357),
 (960, 0.08006407690254357),
 (1005, 0.08006407690254357),
 (1139, 0.08006407690254357),
 (1269, 0.08006407690254357),
 (1289, 0.08006407690254357),
 (1521, 0.08006407690254357),
 (1686, 0.08006407690254357),
 (1747, 0.08006407690254357),
 (2316, 0.08006407690254357),
 (2796, 0.08006407690254357),
 (2865, 0.08006407690254357),
 (2896, 0.08006407690254357),
 (3102, 0.08006407690254357),
 (3140, 0.08006407690254357),
 (3527, 0.08006407690254357),
 (4568, 0.08006407690254357),
 (4641, 0.08006407690254357),
 (234, 0.07944581222989573),
 (486, 0.07927524902574902),
 (39, 0.07897471897389846),
 (96, 0.07897471897389846),
 (112, 0.07897471897389846),
 (242, 0.07897471897389846),
 (341, 0.07897471897389846),
 (402, 0.07897471897389846),
 (854, 0.07897471897389846),
 (901, 0.07897471897389846),
 (922, 0.07897471897389846),
 (1080, 0.07897471897389846),
 (1161, 0.07897471897389846),
 (1519, 0.07897471897389846),
 (2219, 0.07897471897389846),
 (2683, 0.07897471897389846),
 (3164, 0.07897471897389846),
 (153, 0.07884165279854434),
 (1926, 0.07884165279854434),
 (190, 0.0782510703046739),
 (2792, 0.0782510703046739),
 (16, 0.07792865001991967),
 (71, 0.07792865001991967),
 (88, 0.07792865001991967),
 (1113, 0.07792865001991967),
 (1249, 0.07792865001991967),
 (1325, 0.07792865001991967),
 (2330, 0.07792865001991967),
 (3233, 0.07792865001991967),
 (3764, 0.07792865001991967),
 (3851, 0.07792865001991967),
 (4316, 0.07792865001991967),
 (193, 0.07776510597812535),
 (103, 0.07767356373806174),
 (1323, 0.07767356373806174),
 (1577, 0.07767356373806174),
 (1621, 0.07767356373806174),
 (2479, 0.07767356373806174),
 (2671, 0.07767356373806174),
 (2712, 0.07767356373806174),
 (3728, 0.07767356373806174),
 (3988, 0.07767356373806174),
 (4473, 0.07767356373806174),
 (4516, 0.07767356373806174),
 (4737, 0.07767356373806174),
 (222, 0.07710865759549869),
 (286, 0.07710865759549869),
 (607, 0.07710865759549869),
 (1828, 0.07710865759549869),
 (241, 0.07692307692307693),
 (1649, 0.07692307692307693),
 (2163, 0.07692307692307693),
 (2644, 0.07692307692307693),
 (2938, 0.07692307692307693),
 (3091, 0.07692307692307693),
 (4626, 0.07692307692307693),
 (1282, 0.07655590023509527),
 (1924, 0.07655590023509527),
 (2291, 0.07655590023509527),
 (4506, 0.07655590023509527),
 (246, 0.07601486235852867),
 (1659, 0.07601486235852867),
 (37, 0.075955452531275),
 (361, 0.075955452531275),
 (365, 0.075955452531275),
 (792, 0.075955452531275),
 (2128, 0.075955452531275),
 (2916, 0.075955452531275),
 (3028, 0.075955452531275),
 (4268, 0.075955452531275),
 (4341, 0.075955452531275),
 (38, 0.07548513560963972),
 (812, 0.07548513560963972),
 (995, 0.07548513560963972),

In [167]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances= similarity[movie_index]
    movie_list= sorted(list(enumerate(distances)),reverse= True,key= lambda x:x[-1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [169]:
recommend('Batman')

Batman
Batman & Robin
Batman Returns
Batman Begins
The Dark Knight Rises

In [170]:
import pickle
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))